### PR TITLE
Update submission flow

### LINKED ISSUE #131: Submit a Site page
[Figma Source](https://www.figma.com/file/nK6LcMOZMtRAQdIky3PNIA/Showcase?type=design&node-id=3291%3A68596&mode=design&t=oZhs4hIMd1ft8Tab-1)

<table role="table">
<thead>
<tr>
<th>Small</th>
<th>Medium</th>
<th>Large</th>
</tr>
</thead>
<tbody>
<tr>
<td valign="top"><a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/111751264/256118398-dac16638-8636-437f-8734-12aef281d36e.png">(Mobile) Showcase - Submit a Site</a></td>
<td valign="top"><a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/111751264/256117825-41059b68-09ba-4cc8-8dc8-7cec204e5882.png">Showcase - Submit a Site</a></td>
<td valign="top"><a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/111751264/256118401-05a7f5c6-f96e-4eef-b59f-0721e9a52b17.png">(Monitor) Showcase - Submit a Site</a></td>
</tr>
</tbody>
</table>

If the user is not logged in, the page content should not display, instead it should show a log in message:

Showcase - Log in to Submit a Site

After submission, show a success page

Showcase - Your site has been submitted

### PR DESCRIPTION
**Pull request by ryelle**
Fixes #131. This uses the Jetpack contact form process originally created in #44, which is a change from the comment submission that the live site currently uses. That lets us easily add more fields using blocks that already exist, and the moderation process is moved out of comments into the "Feedback" section in wp-admin.

| Logged out | Form | Thanks |
|---|---|---|
| log-in | form | thanks |

To test:

1. Update the page content on the submit page (grab [from the staging site](https://wordpress.org/showcase-v2/wp-admin/post.php?post=91&action=edit) if needed)
2. Make sure the "Submission" template is used on the submit page
3. View the submission page while logged out
4. It should ask you to log in
5. Log in and try again
6. You should see the form
7. Submit a site
8. It should take you to the success page*
9. Your submission should be available on the backend of the site, under Feedback

*&nbsp;Currently the success redirect is not working. @StevenDufresne Did the form submission work correctly on the site last time? I'm wondering if it has something to do with using the form in a pattern. It reminds me of an issue I had in the past (https://github.com/Automattic/jetpack/pull/30764), but that was fixed and that root cause is not in place here.

### CODE REVIEW

**Comment by StevenDufresne** [comment]
> Currently the success redirect is not working. @StevenDufresne Did the form submission work correctly on the site last time?

Yes, it was working.

**Review by StevenDufresne — APPROVED** [review]
I wasn't able to get everything tested but it looks good to merge.

**Comment by ryelle** [comment]
Okay, I've figured out the issue. I'm not sure how it worked for you when the issue did seem to be the pattern. In any case, I've moved the whole submission page into page content on the site (we don't have the same translation or version control requirements here), and now it's working for me. The form could also be put in a template part if we need that to be VC'd, but this will let marketing update the form too if they need to.

**Comment by StevenDufresne** [comment]
🆗 Let's merge this and we can test it on the staging site.

**Pull request merged**
