### PR TITLE
Remove `noreferrer` from Site Link and Site Meta List blocks.

### LINKED ISSUE #250: Remove `noreferrer` from links in Site Link block
Per the feedback in #234, there really shouldn't be `noreferrer` on the site links in the Showcase. It's probably a good thing for receiving sites to see wp.org referrals.

The `noreferrer` needs to be removed here: https://github.com/WordPress/wporg-showcase-2022/blob/94d746f4d7895528ba3ed14fb4f9b59b3b86be78/source/wp-content/themes/wporg-showcase-2022/src/site-link/index.php#L42

### PR DESCRIPTION
**Pull request by ndiego**
Fixes #250 

Removed `noreferrer` from the link in the Site Link and Site Meta List blocks per feedback in #234

### CODE REVIEW

**Comment by renintw** [comment]
I guess the original decision was based on a practice suggesting that using "noopener noreferrer" together is a safe approach. That's probably why it was implemented as such. It seems like "noreferrer" could be safely removed here in the showcase, as I haven't seen URLs containing sensitive user information.

**Review by adamwoodnz — COMMENTED** [review]
LGTM, seems like we'd want to remove it here too?

https://github.com/WordPress/wporg-showcase-2022/blob/main/source/wp-content/themes/wporg-showcase-2022/src/site-meta-list/index.php#L143

**Comment by ndiego** [comment]
> LGTM, seems like we'd want to remove it in the site meta list URL entry too?

Ah, good catch. Just updated the PR to include that.

**Review by adamwoodnz — APPROVED** [review]
LGTM :shipit:

**Pull request merged**
